[project]
name = "duet-workspace"
version = "0.1.0"
description = "Workspace configuration for the Duet runtime and CLI"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pytest>=8.4.2",
]

[tool.uv.workspace]
members = ["python/duet"]
